###########........docker-compose.yml........###########
# Start:  docker compose up -d
# Stop:   docker compose down
version: "3.8"
services: # contaier for the database , name: 'services' can not be changed
  postgre_db: # it is a name that connects the container like services airflow web-server airflow scheduler etc
    image: postgres:16-alpine # alpine for smaller image
    container_name: hydro_postgres
    restart: unless-stopped # restart if it crashes
    env_file:
      - .env
    environment: # from .env file
      POSTGRES_DB: ${PG_DATABASE} #POSTGRES_DB cann't be changed to any other name, it is fixed and also user and password
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

    ports:
      - "${PG_PORT}:5432"

    volumes: # to save the database into local machine so that data would not vanish after restart
      - postgres_data:/var/lib/postgresql/data # postgres_data: folder name could be anything
        # '/var/lib/postgresql/data' not changable
      #The very first time when I build this database, docker automatically look inside my local project folder, find my SQL script, and run it to set up my tables."
      - ./sql/init.sql:/docker-entrypoint-initdb.d/01_init.sql

      # The health check to check if the database is accepting query or not
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - hydro_net # to connect all the containers which use the same network

  # This service runs once to initialize Airflow's metadata tables
  airflow_init:
    #image: apache/airflow:2.7.1-python3.11
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgre_db:
        condition: service_healthy # Waits until your custom tables are created
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@postgre_db:5432/${PG_DATABASE}"
    # Fix: Put the entrypoint and command into a single valid bash execution block
    command: >
      bash -c "airflow db init && 
      airflow users create --username airflow --password airflow --firstname Admin --lastname Admin --role Admin --email admin@example.com"
    networks:
      - hydro_net

  airflow_webserver:
    #image: apache/airflow:2.7.1-python3.11
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_webserver
    restart: unless-stopped
    depends_on:
      - postgre_db
    env_file:
      - .env
    environment:
      NVE_API_KEY: "${NVE_API_KEY}"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@postgre_db:5432/${PG_DATABASE}"
      AIRFLOW__CORE__FERNET_KEY: "ggiJU6dFtJRvN_0nlYqoSUG6KlSutrOnvjVbtB3sGZA="
      AIRFLOW__WEBSERVER__SECRET_KEY: "taz_secret_key"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      PYTHONPATH: /opt/airflow
    command: airflow webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./extract:/opt/airflow/extract
      - ./transform:/opt/airflow/transform
      - ./load:/opt/airflow/load
      - ./dbt/hydro_project:/opt/airflow/dbt

    ports:
      - "8080:8080"
    networks:
      - hydro_net

  airflow_scheduler:
    #image: apache/airflow:2.7.1-python3.11
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_scheduler
    restart: unless-stopped
    depends_on:
      - postgre_db
    env_file:
      - .env
    environment:
      NVE_API_KEY: "${NVE_API_KEY}"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@postgre_db:5432/${PG_DATABASE}"
      AIRFLOW__CORE__FERNET_KEY: "ggiJU6dFtJRvN_0nlYqoSUG6KlSutrOnvjVbtB3sGZA="
      AIRFLOW__WEBSERVER__SECRET_KEY: "taz_secret_key"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      PYTHONPATH: /opt/airflow
    command: airflow scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./extract:/opt/airflow/extract
      - ./transform:/opt/airflow/transform
      - ./load:/opt/airflow/load
      - ./.dbt:/home/airflow/.dbt
      - ./dbt/hydro_project:/opt/airflow/dbt

    networks:
      - hydro_net

  # streamlit:
  #   image: python:3.11
  #   networks:
  #     - hydro_net
  #   ...

volumes:
  postgres_data: # it contains all the database or multiple database inside it not only the "hydro" database
    driver: local

networks:
  hydro_net:
    driver: bridge
